[tool.poetry]
name = "rtc-sim"
version = "0.1.0"
description = ""
authors = ["Takeru Hayashi <takeruhayashi@g.ucla.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
